apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: machine.telemetry.dlq
  namespace: streaming
  labels:
    strimzi.io/cluster: local-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000
    segment.bytes: 107374182
